var numbers = [1, 2, 3];
console.log(numbers);
var names = ["Alice", "Bob", "Charlie"];
console.log(names);
var fruits = [];
fruits.push("Apple");
fruits.push("Banana");
fruits.push("Orange");
console.log(fruits);
var message = "Hello Typescript";
console.log(message);
var text = "Typescript";
var trimText = text.trim();
console.log(trimText);
var age = 25;
console.log(age);
var isStudent = true;
console.log(isStudent);
var ids = [1, 2, 3];
console.log(ids);
var names1 = ["Alice", "Bob", "Charlie"];
var exists = names1.includes("Charlie");
console.log(exists);
var text1 = "Typescript";
var upperCaseText1 = text1.toUpperCase();
console.log(upperCaseText1);
